import smtplib
from email.mime.text import MIMEText

sender = "mail@gmail.com"
password = "your password here"  # Replace with your actual password or use an app password for Gmail
receiver = "mail@gmail.com"

subject = "Pipeline Completed Successfully"

html_body = """
<html>
<head>
<style>
body {
    font-family: Arial, sans-serif;
    background-color: #f4f6f9;
    color: #333333;
}

.container {
    max-width: 650px;
    margin: auto;
    background: white;
    padding: 25px;
    border-radius: 10px;
    border: 1px solid #dddddd;
}

.header {
    background-color: #2E86C1;
    color: white;
    text-align: center;
    padding: 15px;
    border-radius: 8px;
}

.success {
    color: green;
    font-weight: bold;
}

.footer {
    margin-top: 20px;
    font-size: 13px;
    color: gray;
}
</style>
</head>

<body>

<div class="container">

<div class="header">
<h2>🚀 Data Engineering Pipeline Report</h2>
</div>

<p>Hello,</p>

<p>
Your <strong>Data Engineering Pipeline</strong> has completed
<b class="success">SUCCESSFULLY</b>.
</p>

<h3>Pipeline Execution Summary</h3>

<table border="1" cellpadding="10" cellspacing="0" width="100%" style="border-collapse:collapse;">
<tr>
<th align="left">Stage</th>
<th>Status</th>
</tr>

<tr><td>📥 Data Ingestion</td><td>✅ Completed</td></tr>
<tr><td>🛠️ Staging Layer</td><td>✅ Completed</td></tr>
<tr><td>🥉 Bronze Layer</td><td>✅ Completed</td></tr>
<tr><td>✔ Data Validation</td><td>✅ Completed</td></tr>
<tr><td>🥈 Silver Layer</td><td>✅ Completed</td></tr>
<tr><td>🔄 Business Transformations</td><td>✅ Completed</td></tr>
<tr><td>📝 SCD Type 1</td><td>✅ Completed</td></tr>
<tr><td>📝 SCD Type 2</td><td>✅ Completed</td></tr>
<tr><td>🥇 Gold Layer</td><td>✅ Completed</td></tr>
<tr><td>🗄 PostgreSQL Load</td><td>✅ Completed</td></tr>
<tr><td>📊 Metadata Generation</td><td>✅ Completed</td></tr>
<tr><td>📋 Audit Logging</td><td>✅ Completed</td></tr>
</table>

<br>

<h3>Execution Status</h3>

<ul>
<li>Overall Status : <b style="color:green;">SUCCESS</b></li>
<li>Data Warehouse Updated Successfully</li>
<li>Pipeline Executed Without Errors</li>
<li>All Tasks Finished Successfully</li>
</ul>

<hr>

<p>
This is an automated notification generated by the
<strong>Airflow Data Engineering Pipeline</strong>.
</p>

<div class="footer">
Regards,<br>
<b>Thilak Ragav</b><br>
Data Engineering Automation System
</div>

</div>

</body>
</html>
"""

msg = MIMEText(html_body, "html")

msg["Subject"] = "✅ Data Engineering Pipeline Completed Successfully"
msg["From"] = sender
msg["To"] = receiver

server = smtplib.SMTP("smtp.gmail.com", 587)
server.starttls()
server.login(sender, password)
server.send_message(msg)
server.quit()

print("Email Sent Successfully")